import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static void main(String[] args) {
    int[] answerOne = roll(7);
    System.out.println(Arrays.toString(answerOne));
    }

    public static int[] roll(int n){
        int[] rollArray = new int[n];
        for(int i = 0; i < n; i++){        //max = 6 | min =1
            rollArray[i] = (int)(Math.random() * ((6 - 1) + 1)) + 1;
        }
        return rollArray;
    }


//    public boolean someLibraryMethod() {
//        return true;
//    }
}
