import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    public static void main(String[] args) {

        //First problem
    int[] answerOne = roll(7);
    System.out.println(Arrays.toString(answerOne));

    //Second problem
        int[] parameter = {9,9,9,9,9};
        int answerTwo = averageOfArray(parameter);
        System.out.println("" + answerTwo);

    }

    public static int[] roll(int n){
        int[] rollArray = new int[n];
        for(int i = 0; i < n; i++){        //max = 6 | min =1
            rollArray[i] = (int)(Math.random() * ((6 - 1) + 1)) + 1;
        }
        return rollArray;
    }

    public static int averageOfArray(int[] arrayToCalc){
        int average = 0;
        for (int element : arrayToCalc){
            average += element;
        }
        average = average / arrayToCalc.length;
        return average;
    }

//    public boolean someLibraryMethod() {
//        return true;
//    }
}
