import java.nio.file.FileSystems;
import java.nio.file.Path;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {

        // find an image
        Path imagePath = FileSystems.getDefault().getPath("resources", "test.BMP");

        // read the image
        Bitmap bmp = new Bitmap(imagePath);

        // alter the image
        bmp.flipHorizontally();

        // output the image
        bmp.save(FileSystems.getDefault().getPath("resources", "test_after.BMP"));

    }
}
























