import java.awt.*;
import java.awt.event.*;
import java.awt.image.*;
import java.io.*;
import javax.imageio.*;
import javax.swing.*;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public String getGreeting(){
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    }


}
