import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        Path gates = Paths.get("resources/gates.js");
        jsLinter(gates);
    }

    public static void jsLinter(Path file){
        try(BufferedReader reader = Files.newBufferedReader(file)){
            String currentLine = "";
            int line = 0;
            while(currentLine != null){
                if(!currentLine.isEmpty() && !currentLine.endsWith("{") && !currentLine.endsWith("}") && !currentLine.endsWith("if") && !currentLine.endsWith("else") && !currentLine.endsWith(";") & !currentLine.endsWith("//")) {
                    System.out.println("Line " + line + ": missing semicolon.");
                }
                line++;
                currentLine = reader.readLine();
            }
        }
        catch(IOException e){
            System.out.println(e);
        }
    }

    public String getGreeting() {
        return "Hello world.";
    }
}